kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test
nodes:
- role: control-plane
  image: nestybox/kindestnode:v1.19.4
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 90
    protocol: TCP
  - containerPort: 443
    hostPort: 994
    protocol: TCP
- role: worker
  image: nestybox/kindestnode:v1.19.4
- role: worker
  image: nestybox/kindestnode:v1.19.4
- role: worker
  image: nestybox/kindestnode:v1.19.4